-- Simple events schema update
ALTER TABLE events ADD COLUMN IF NOT EXISTS category VARCHAR(100) DEFAULT 'workshop';
ALTER TABLE events ADD COLUMN IF NOT EXISTS tags TEXT[];
ALTER TABLE events ADD COLUMN IF NOT EXISTS start_time TIME;
ALTER TABLE events ADD COLUMN IF NOT EXISTS end_time TIME;
ALTER TABLE events ADD COLUMN IF NOT EXISTS venue_name VARCHAR(255);
ALTER TABLE events ADD COLUMN IF NOT EXISTS venue_address TEXT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS venue_city VARCHAR(100);
ALTER TABLE events ADD COLUMN IF NOT EXISTS latitude DECIMAL(10, 8);
ALTER TABLE events ADD COLUMN IF NOT EXISTS longitude DECIMAL(11, 8);
ALTER TABLE events ADD COLUMN IF NOT EXISTS min_participants INTEGER DEFAULT 1;
ALTER TABLE events ADD COLUMN IF NOT EXISTS currency VARCHAR(10) DEFAULT 'VND';
ALTER TABLE events ADD COLUMN IF NOT EXISTS early_bird_price DECIMAL(10,2);
ALTER TABLE events ADD COLUMN IF NOT EXISTS early_bird_until DATE;
ALTER TABLE events ADD COLUMN IF NOT EXISTS cover_image TEXT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS gallery_images TEXT[];
ALTER TABLE events ADD COLUMN IF NOT EXISTS video_url TEXT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS audio_preview TEXT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS event_type VARCHAR(50) DEFAULT 'public';
ALTER TABLE events ADD COLUMN IF NOT EXISTS age_restriction VARCHAR(50) DEFAULT 'all';
ALTER TABLE events ADD COLUMN IF NOT EXISTS language VARCHAR(10) DEFAULT 'vi';
ALTER TABLE events ADD COLUMN IF NOT EXISTS difficulty_level VARCHAR(50) DEFAULT 'beginner';
ALTER TABLE events ADD COLUMN IF NOT EXISTS equipment_provided TEXT[];
ALTER TABLE events ADD COLUMN IF NOT EXISTS equipment_needed TEXT[];
ALTER TABLE events ADD COLUMN IF NOT EXISTS amenities TEXT[];
ALTER TABLE events ADD COLUMN IF NOT EXISTS organizer_name VARCHAR(255);
ALTER TABLE events ADD COLUMN IF NOT EXISTS organizer_email VARCHAR(255);
ALTER TABLE events ADD COLUMN IF NOT EXISTS organizer_phone VARCHAR(20);
ALTER TABLE events ADD COLUMN IF NOT EXISTS organizer_bio TEXT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS requirements TEXT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS what_to_bring TEXT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS cancellation_policy TEXT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS refund_policy TEXT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS facebook_event TEXT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS instagram_post TEXT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS hashtags TEXT[];
ALTER TABLE events ADD COLUMN IF NOT EXISTS featured BOOLEAN DEFAULT FALSE;
ALTER TABLE events ADD COLUMN IF NOT EXISTS promoted BOOLEAN DEFAULT FALSE;













