import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { CacheFirst } from 'workbox-strategies';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';
import { ExpirationPlugin } from 'workbox-expiration';

// Precache all assets generated by Vite build process
precacheAndRoute(self.__WB_MANIFEST || []);
cleanupOutdatedCaches();

// Cache images (jpg, png, webp, svg, etc.) with CacheFirst strategy
registerRoute(
  ({ request }) => request.destination === 'image',
  new CacheFirst({
    cacheName: 'music-space-images',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200]
      }),
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 30 * 24 * 60 * 60 // 30 Days
      })
    ]
  })
);

// Cache fonts with CacheFirst strategy
registerRoute(
  ({ request }) => request.destination === 'font',
  new CacheFirst({
    cacheName: 'music-space-fonts',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200]
      }),
      new ExpirationPlugin({
        maxEntries: 20,
        maxAgeSeconds: 365 * 24 * 60 * 60 // 1 Year
      })
    ]
  })
);

// Single Page Application (SPA) navigation routing
// Network-first for document requests, fallback to cached index.html
const navigationHandler = async (params) => {
  try {
    // Attempt to fetch from network first
    return await fetch(params.request);
  } catch (error) {
    // If offline, return the precached index.html (App Shell)
    const cachedResponse = await caches.match('/index.html');
    if (cachedResponse) {
      return cachedResponse;
    }
    // Fallback to custom offline message if index.html is somehow not available
    return new Response(
      '<h1>Offline Mode</h1><p>Music Space đang ngoại tuyến. Vui lòng kết nối Internet để tiếp tục.</p>',
      {
        headers: { 'Content-Type': 'text/html; charset=utf-8' }
      }
    );
  }
};

registerRoute(new NavigationRoute(navigationHandler));

// Handle Web Push Notification event
self.addEventListener('push', (event) => {
  let payload = {};
  if (event.data) {
    try {
      payload = event.data.json();
    } catch (e) {
      payload = {
        title: 'Music Space',
        body: event.data.text()
      };
    }
  }

  const title = payload.title || 'Music Space';
  const options = {
    body: payload.body || 'Bạn có thông báo mới từ không gian âm nhạc!',
    icon: payload.icon || '/icon-192.png',
    badge: payload.badge || '/icon-192.png',
    vibrate: [100, 50, 100],
    data: {
      url: payload.url || '/'
    }
  };

  event.waitUntil(
    self.registration.showNotification(title, options)
  );
});

// Handle click event on the Push Notification
self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  const targetUrl = event.notification.data?.url || '/';

  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
      // Check if there is already a window open with the target URL path
      for (let i = 0; i < windowClients.length; i++) {
        const client = windowClients[i];
        const clientPathname = new URL(client.url).pathname;
        const targetPathname = new URL(targetUrl, client.url).pathname;
        
        if (clientPathname === targetPathname && 'focus' in client) {
          return client.focus();
        }
      }
      // If no open tab matches, open a new one
      if (clients.openWindow) {
        return clients.openWindow(targetUrl);
      }
    })
  );
});

// Handle service worker lifecycle updates
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});
